kind: ConfigMap 
apiVersion: v1 
metadata:
  name: vulnscan-cronjob-template # TODO: update template name
  namespace: {{ .Values.ksNamespace }}
  labels:
    app: {{ .Values.global.cloudConfig }}
    tier: {{ .Values.global.namespaceTier }}
data:
  cronjobTemplate: |-
    {{ tpl (.Files.Get "assets/armo-vulnscan-cronjob-full.yaml") . }}
